services:
  postgres:
    image: postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USERNAME: $[POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  admin:
      image: adminer
      depends_on:
        - postgres
      ports:
        - "8080:8080"
      networks:
        - postgres
      restart: unless-stopped
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin:
  mongodb_data: